# Minimal astgrep Configuration

[general]
verbose = false

[analysis]
languages = ["java", "javascript", "python"]
output_format = "text"

[filtering]
min_severity = "warning"
exclude_patterns = [
"**/test/**",
"**/node_modules/**"
]

[rules]
rules_directory = "rules"
