[package]
name = "cr-matcher"
version = "0.1.0"
edition = "2021"
description = "Pattern matching engine for CR-SemService"

[dependencies]
cr-core = { path = "../cr-core" }
cr-ast = { path = "../cr-ast" }
regex.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile = "3.8"
