# Cargo 配置文件 - 交叉编译设置

# Linux x86_64 musl 目标（静态链接）
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

# Linux aarch64 musl 目标（ARM64 静态链接）
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

# Linux x86_64 gnu 目标（动态链接）
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

# 构建配置
[build]
# 默认使用所有 CPU 核心
jobs = 8

# 网络配置
[net]
# 使用 git CLI 而不是 libgit2（某些情况下更稳定）
git-fetch-with-cli = true

# 注册表配置
[registries.crates-io]
protocol = "sparse"

# 别名配置
[alias]
# 快速交叉编译到 Linux x86_64
build-linux = "build --release --target x86_64-unknown-linux-musl"
# 快速交叉编译到 Linux ARM64
build-linux-arm = "build --release --target aarch64-unknown-linux-musl"
# 编译所有 Linux 目标
build-linux-all = "build --release --target x86_64-unknown-linux-musl --target aarch64-unknown-linux-musl"

