[package]
name = "cr-ast"
version = "0.1.0"
edition = "2021"
description = "Universal AST definitions for CR-SemService"

[dependencies]
cr-core = { path = "../cr-core" }
serde.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile = "3.8"
